### ISSUE TITLE
Migrate to `windows-rs`?

### ISSUE THREAD

**Issue by dilawar** [SubconsciousCompute/systray2#1]

**Comment by sn99** [comment]
@dilawar Done with few other changes: https://github.com/Actyx/systray2/pull/1

We can also use more actively maintained projects like: 
- [native-windows-gui](https://github.com/gabdube/native-windows-gui) : [system_tray_d.rs](https://github.com/gabdube/native-windows-gui/blob/master/native-windows-gui/examples/system_tray_d.rs)
- [tao](https://github.com/tauri-apps/tao) : `cargo run --features tray --example system_tray`
- [tray-item-rs](https://github.com/olback/tray-item-rs)

**Comment by dilawar** [comment]
Send a PR to this repo.

**Comment by sn99** [comment]
Done at #2
